import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Restaurantly - Modern Restaurant Website</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className="text-black">A resturent website</div>
			</main>
		</div>
	);
}
